//! Astraeon on-chain guard — a Rialo Venus workflow.
//!
//! This program is the on-chain counterpart of the off-chain guard engine in
//! `src/lib/astraeon/`. It keeps an on-chain policy and an audit counter, and
//! every submitted action is evaluated against that policy *inside the program*.
//! The decision and running counters are persisted in workflow state, so the
//! policy boundary is enforced by the chain (REX), not just by the frontend.
//!
//! Instructions generated by `rialo!`:
//!   - `initialize(max_amount, allow_withdraw, allowed_assets)`  — set the policy
//!   - `evaluate(action, asset, amount, destination)`             — decide + log
//!
//! Deploy: see PROGRAM.md at the repository root of this crate.

use rialo_venus_proc_macro::rialo;

rialo! {
    workflow {
        state {
            /// Maximum amount in kelvin a single action may move.
            policy_max_amount: u64,

            /// Whether withdrawal-type actions are permitted at all.
            policy_allow_withdraw: bool,

            /// Comma-separated allowlist of assets (e.g. "BTC,ETH").
            policy_allowed_assets: String,

            /// Running counters, written on-chain after every invocation.
            actions_evaluated: u64,
            actions_allowed: u64,
            actions_blocked: u64,

            /// Human-readable last decision, e.g. "DENY: amount exceeds policy".
            last_decision: String,
        }

        program {
            use rialo_s_program::{ entrypoint::ProgramResult, msg };

            /// Configure the on-chain policy. Call once during deployment.
            initiating fn initialize(
                &mut self,
                max_amount: u64,
                allow_withdraw: bool,
                allowed_assets: String,
            ) -> ProgramResult {
                msg!("Guard::Initialize max={} withdraw={} assets={}", max_amount, allow_withdraw, allowed_assets);
                self.policy_max_amount = max_amount;
                self.policy_allow_withdraw = allow_withdraw;
                self.policy_allowed_assets = allowed_assets;
                self.last_decision = "policy initialized".to_string();
                Ok(())
            }

            /// Evaluate an agent action against the on-chain policy and record
            /// the decision in workflow state. `action` is the action kind
            /// (e.g. "buy", "swap", "withdraw"), `asset` an asset label, and
            /// `amount` the value in kelvin.
            initiating fn evaluate(
                &mut self,
                action: String,
                asset: String,
                amount: u64,
                destination: String,
            ) -> ProgramResult {
                msg!("Guard::Evaluate {} {} {} {}", action, asset, amount, destination);
                self.actions_evaluated += 1;

                let mut allowed = true;
                let mut reason = "all checks passed".to_string();

                if action == "withdraw" && !self.policy_allow_withdraw {
                    allowed = false;
                    reason = "withdraw disabled by policy".to_string();
                }
                if amount > self.policy_max_amount {
                    allowed = false;
                    reason = "amount exceeds policy max".to_string();
                }
                if !self.policy_allowed_assets.contains(&asset) {
                    allowed = false;
                    reason = "asset not in allowlist".to_string();
                }

                if allowed {
                    self.actions_allowed += 1;
                    self.last_decision = format!("ALLOW: {reason}");
                } else {
                    self.actions_blocked += 1;
                    self.last_decision = format!("DENY: {reason}");
                }
                msg!("Guard::Decision {}", self.last_decision);
                Ok(())
            }

            /// End a workflow run with the accumulated counters.
            terminating fn finish(&mut self) -> ProgramResult {
                msg!(
                    "Guard::Finished evaluated={} allowed={} blocked={}",
                    self.actions_evaluated,
                    self.actions_allowed,
                    self.actions_blocked
                );
                Ok(())
            }
        }
    }
}
